# kubernetes/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nalabheemas-bot-deployment  # <-- New Name
  namespace: nalabheemas-bot       # <-- New Namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nalabheemas-bot # <-- New Label
  template:
    metadata:
      labels:
        app: nalabheemas-bot # <-- New Label
    spec:
      containers:
      - name: bot-container # <-- New Container Name
        image: kishanthorat111/nalabheemas-bot:latest # <-- New Docker Image
        resources: # Add resource limits for stability
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
          - secretRef:
              name: nalabheemas-secrets # <-- New Secret
        volumeMounts:
        - name: gcp-credentials-volume
          mountPath: /app/credentials.json
          subPath: credentials.json
      volumes:
      - name: gcp-credentials-volume
        secret:
          secretName: nalabheemas-secrets # <-- New Secret
          items:
          - key: credentials.json
            path: credentials.json